Repository FoodieLog/foodie-log-client, pull requests merged in 2023-08, with the labels that each got.

#9 Feat auth
  next.config.js
  src/app/entrance/page.tsx
  src/app/signup/page.tsx
  src/components/Button/index.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature

#17 Feat: auth 관련 페이지 UI 구현
  public/images/kakao_login_medium_wide.png
  src/app/accounts/login/page.tsx
  src/app/accounts/password/change/page.tsx
  src/app/accounts/password/page.tsx
  src/app/accounts/signup/agree/page.tsx
  src/app/accounts/signup/email-code/page.tsx
  src/app/accounts/signup/page.tsx
  src/app/accounts/signup/profile-settings/page.tsx
  src/app/entrance/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/signup/page.tsx
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Auth/PasswordCode.tsx
  src/components/Auth/SignUpCode.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Auth/SignUpProfile.tsx
  src/components/Auth/SignUpTerms.tsx
  src/components/Auth/index.tsx
  src/components/Button/BackButton.tsx
  src/components/Button/index.tsx
  src/styles/globals.css
Labels: ✨ Feature

#18 Feat: 마이페이지-랜딩페이지 UI 구현
  src/app/[id]/map/page.tsx
  src/app/[id]/page.tsx
  src/app/layout.tsx
  src/components/Mypage/index.tsx
  src/styles/globals.css
Labels: ✨ Feature

#26 Recommend : 음식점 썸네일 이미지 저장 및 공통 컴포넌트(ShopCard) 구현
  public/images/foodCategoryIcons/asian.png
  public/images/foodCategoryIcons/bakery.png
  public/images/foodCategoryIcons/bar.png
  public/images/foodCategoryIcons/cafe.png
  public/images/foodCategoryIcons/chicken.png
  public/images/foodCategoryIcons/default.png
  public/images/foodCategoryIcons/dessert.png
  public/images/foodCategoryIcons/fastfood.png
  public/images/foodCategoryIcons/healthy.png
  public/images/foodCategoryIcons/hotdog.png
  public/images/foodCategoryIcons/index.ts
  public/images/foodCategoryIcons/indian.png
  public/images/foodCategoryIcons/italian.png
  public/images/foodCategoryIcons/japanese.png
  public/images/foodCategoryIcons/korean.png
  public/images/foodCategoryIcons/meat.png
  public/images/foodCategoryIcons/noodles.png
  public/images/foodCategoryIcons/organic.png
  public/images/foodCategoryIcons/pizza.png
  public/images/foodCategoryIcons/riceMeal.png
  public/images/foodCategoryIcons/sandwich.png
  public/images/foodCategoryIcons/sashimi.png
  public/images/foodCategoryIcons/seafood.png
  public/images/foodCategoryIcons/soup.png
  public/images/foodCategoryIcons/thai.png
  src/components/Feed.tsx
  src/components/ShopCard.tsx
  src/components/ShopThumb.tsx
  src/utils/iconUtils.ts
Labels: ♻️ Refactor

#28 Recommend : 식당 상세 정보 페이지 구현 및 카카오 지도 API 적용
  next.config.js
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/main/layout.tsx
  src/app/main/recommend/page.tsx
  src/app/main/restaurants/[id]/page.tsx
  src/components/AreaSelector.tsx
  src/components/Bottombar.tsx
  src/components/Button/BackButtonMain.tsx
  src/components/Feed.tsx
  src/components/Feeds.tsx
  src/components/KakaoMap.tsx
  src/components/RestaurantDetail.tsx
  src/components/ShopCard.tsx
  src/components/ShopThumb.tsx
  src/components/ShopThumbList.tsx
  src/components/Topbar.tsx
  src/hooks/useHideOnScroll.ts
  src/utils/dummyDataUtils.ts
  tailwind.config.ts
  tsconfig.json
Labels: 🐛 Bug, ♻️ Refactor, ✨ Feature

#29 Feat: auth 관련 페이지 - 유효성 검사, api 연결 구현
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Auth/PasswordCode.tsx
  src/components/Auth/SignUpCode.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Auth/SignUpProfile.tsx
  src/components/Auth/SignUpTerms.tsx
  src/components/Button/index.tsx
  src/components/Line/index.tsx
  src/constants/index.ts
  src/services/auth.ts
  src/services/index.ts
  src/store/useSignUpStore.ts
  src/styles/globals.css
  src/types/apiTypes.ts
Labels: ✨ Feature

#33 Feat auth 카카오 로그인 기능 구현
  .env
  .gitignore
  src/app/layout.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Auth/SignUpProfile.tsx
  src/components/Auth/SignUpTerms.tsx
  src/constants/index.ts
  src/services/auth.ts
  src/services/index.ts
  src/services/kakao.ts
  src/store/useKakaoStore.ts
  src/store/useSignUpStore.ts
  src/types/apiTypes.ts
Labels: ✨ Feature

#34 Feat: auth 관련 페이지 코드 수정
  .env
  src/app/auth/kakao/callback/page.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Auth/PasswordCode.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Auth/SignUpTerms.tsx
  src/services/auth.ts
  src/store/useKakaoStore.ts
  src/store/useSignUpStore.ts
Labels: ✨ Feature

#38 Feat: auth 관련 페이지 수정 및 하단 바 마이페이지 url 수정
  src/app/auth/kakao/callback/page.tsx
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Auth/PasswordCode.tsx
  src/components/Bottombar.tsx
  src/components/Mypage/index.tsx
  src/services/auth.ts
  src/store/useSignUpStore.ts
  src/types/apiTypes.ts
Labels: ♻️ Refactor
