Repository FoodieLog/foodie-log-client, pull requests merged in 2024-03, with the labels that each got.

#182 feat: 유저 검색 컴포넌트 모듈 세분화 및 최근 검색 내역 기능 구현
  src/assets/images/index.ts
  src/assets/images/logo/userImage.png
  src/components/Auth/LoginForm.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Common/Button/KaKaoLoginButton.tsx
  src/components/SearchUser/SearchHistory.tsx
  src/components/SearchUser/SearchUser.tsx
  src/components/SearchUser/SearchUserList.tsx
  src/store/useSearchStore.ts
  src/utils/getKey.ts
Labels: 🎨 UI, ♻️ Refactor, ✨ Feature

#184 [Feat] #175 피드 작성 페이지 수정 디자인 적용
  src/app/main/home/page.tsx
  src/app/main/layout.tsx
  src/app/main/recommend/page.tsx
  src/assets/icons/common/arrow_back_ios.svg
  src/assets/images/basic/basic_thumb.svg
  src/assets/images/index.ts
  src/components/Common/DropDown/DropDown.tsx
  src/components/Common/Header/index.tsx
  src/components/Feed/FeedImageSlide.tsx
  src/components/Feed/Feeds.tsx
  src/components/Main/GlobalNavigation.tsx
  src/components/PostForm/EmptyList.tsx
  src/components/PostForm/PostContent.tsx
  src/components/PostForm/PostContentShopItem.tsx
  src/components/PostForm/PostFeedImage.tsx
  src/components/PostForm/PostImage.tsx
  src/components/PostForm/PostImageItems.tsx
  src/components/PostForm/PostImageList.tsx
  src/components/PostForm/PostSearch.tsx
  src/components/PostForm/PostShopItem.tsx
  src/components/PostForm/PostShopList.tsx
  src/components/SearchUser/SearchInput.tsx
  src/constants/index.ts
  src/constants/navigation.ts
  src/store/usePostStore.ts
  src/types/post.ts
Labels: 🎨 UI, ♻️ Refactor

#186 feat: 회원가입 컴포넌트 코드 리팩토링 및 중복 ui 컴포넌트 분리
  src/app/auth/kakao/callback/page.tsx
  src/components/Auth/AuthCheck.ts
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/CodeInput.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Auth/PasswordCode.tsx
  src/components/Auth/SignUpCode.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Auth/SignUpProfile.tsx
  src/components/Auth/SignUpTerms.tsx
  src/constants/terms.ts
  src/constants/toast.ts
  src/services/apiFeed.ts
  src/store/useSignUpStore.ts
  src/types/signupTypes.ts
  src/utils/date.ts
Labels: ♻️ Refactor

#187 [Feat] #185 설정 및 개인정보 수정 페이지, 비밀번호 재설정 디자인 수정
  src/app/accounts/password/page.tsx
  src/app/main/settings/badge/page.tsx
  src/app/main/settings/password/page.tsx
  src/assets/icons/common/WarningCircle.svg
  src/assets/icons/common/notification_small.svg
  src/assets/icons/index.ts
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/CodeInput.tsx
  src/components/Auth/PasswordAuth.tsx
  src/components/Auth/PasswordCode.tsx
  src/components/Common/Button/index.tsx
  src/components/Common/Error/index.tsx
  src/components/Settings/CompleteChangePassword.tsx
  src/components/Settings/MySettings.tsx
  src/components/Settings/SettingBadge.tsx
  src/components/Settings/SettingListItem.tsx
  src/components/Settings/SettingPassword.tsx
  src/services/settings.ts
  src/styles/globals.css
Labels: 🎨 UI, ♻️ Refactor

#192 식당 상세정보 페이지 및 맛집 지도 페이지 로직 최적화
  components/ui/dialog.tsx
  components/ui/dialog/index.tsx
  components/ui/drawer.tsx
  package-lock.json
  package.json
  src/app/main/liked/page.tsx
  src/app/main/restaurants/[id]/page.tsx
  src/app/main/restaurants/[restaurantId]/page.tsx
  src/components/Common/Card/ShopCard.tsx
  src/components/Common/Drawer/Drawer.tsx
  src/components/Map/KakaoMap.tsx
  src/components/Map/MyListMap.tsx
  src/components/Map/MyMap.tsx
  src/components/Mypage/MyMap.tsx
  src/components/Mypage/MyShopItem.tsx
  src/components/Restaurant/RestaurantDetail.tsx
  src/constants/toast.ts
  src/hooks/mutations/useLikeShopMutations.ts
  src/hooks/queries/useMyMapQuery.ts
  src/hooks/queries/useRestaurantDetailQuery.ts
  src/services/restaurant.ts
  src/types/mypage.ts
Labels: ♻️ Refactor, ✨ Feature

#194 [Feat] #189 지역별 맛집 추천 페이지 디자인 수정
  public/svgs/arrow_drop_down.svg
  src/app/main/recommend/page.tsx
  src/app/main/restaurants/reviews/[id]/page.tsx
  src/components/Common/Card/ShopCard.tsx
  src/components/Common/FeedThumbnailList/index.tsx
  src/components/Feed/Feed.tsx
  src/components/Restaurant/AreaList.tsx
  src/components/Restaurant/AreaOptionItem.tsx
  src/components/Restaurant/AreaOptionList.tsx
  src/components/Restaurant/AreaSelector.tsx
  src/components/Restaurant/RestaurantFeedList.tsx
  src/components/Restaurant/ShopFeedItem.tsx
  src/components/Restaurant/ShopFeedList.tsx
  src/components/Restaurant/ShopThumb.tsx
  src/components/Restaurant/ShopThumbList.tsx
  src/hooks/queries/useRecommendQuery.ts
  src/hooks/queries/useRestaurantDetailQuery.ts
  src/hooks/useDetectClose.ts
  src/services/apiRestaurant.ts
  src/services/restaurant.ts
  src/types/recommend.ts
  src/types/restaurant.ts
  src/utils/iconUtils.ts
  tailwind.config.ts
Labels: 🎨 UI, ♻️ Refactor

#196 Refactor: 마이페이지 - 리액트 쿼리 마이그레이션 및 컴포넌트 모듈화 / 로그인 페이지 - 스타일 수정
  package-lock.json
  package.json
  src/assets/icons/common/FullHeartStraight.svg
  src/assets/icons/common/HeartStraight.svg
  src/components/Auth/LoginForm.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Common/Button/FollowButton.tsx
  src/components/Common/Line/index.tsx
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedHeader.tsx
  src/components/Feed/FeedInteraction.tsx
  src/components/Feed/FeedUserCard.tsx
  src/components/Feed/Feeds.tsx
  src/components/Map/MyMap.tsx
  src/components/Map/MyShopItem.tsx
  src/components/Mypage/MyFeedThumnail.tsx
  src/components/Mypage/MyFriendList.tsx
  src/components/Mypage/MyMap.tsx
  src/components/Mypage/MyProfile.tsx
  src/components/Mypage/MyProfileSettings.tsx
  src/components/Mypage/MyProfileTabContent.tsx
  src/hooks/mutations/useFollowMutaton.ts
  src/hooks/mutations/useMutaton.ts
  src/hooks/queries/useMyFollowersQuery.ts
  src/hooks/queries/useMyPageQuery.ts
  src/hooks/queries/useQuery.ts
  src/services/mypage.ts
  src/styles/globals.css
  src/types/mypage.ts
Labels: 🎨 UI, ♻️ Refactor, ✨ Feature

#199 식당 페이지 및 맛집 지도 페이지 UI 변경
  src/app/main/restaurants/[restaurantId]/feed/page.tsx
  src/assets/icons/index.ts
  src/assets/icons/tag/asian_selected.svg
  src/assets/icons/tag/bar_selected.svg
  src/assets/icons/tag/cafe_selected.svg
  src/assets/icons/tag/dessert_selected.svg
  src/assets/icons/tag/japanese_selected.svg
  src/assets/icons/tag/korean_selected.svg
  src/assets/icons/tag/snack_selected.svg
  src/assets/icons/tag/western_selected.svg
  src/components/Common/Card/ShopCard.tsx
  src/components/Common/Drawer/Drawer.tsx
  src/components/Map/MyListMap.tsx
  src/components/Map/MyMap.tsx
  src/components/Restaurant/RestaurantCategorySlider.tsx
  src/components/Restaurant/RestaurantDetail.tsx
  src/constants/index.ts
  src/constants/tag.ts
  src/utils/iconUtils.ts
  tailwind.config.ts
Labels: 🎨 UI, ♻️ Refactor

#202 [Refactor] #201 input global css 수정
  src/assets/icons/common/Eye.svg
  src/assets/icons/common/EyeSlash.svg
  src/assets/icons/index.ts
  src/components/Settings/SettingPassword.tsx
  src/hooks/useToggleShowPassword.ts
  src/styles/globals.css
Labels: 🎨 UI, ✨ Feature

#203 refactor: 회원가입 페이지 디자인 수정 및 리팩토링
  src/app/accounts/layout.tsx
  src/assets/icons/common/checkedcircle.svg
  src/assets/icons/common/uncheckedcircle.svg
  src/assets/icons/index.ts
  src/components/Auth/CodeInput.tsx
  src/components/Auth/SignUpCode.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Auth/SignUpTermsModal.tsx
  src/components/Common/Button/index.tsx
Labels: 🎨 UI, ♻️ Refactor

#204 [Feat] #195 피드 작성 페이지 디자인 및 버그 수정
  src/app/main/layout.tsx
  src/assets/icons/common/edit.svg
  src/assets/icons/index.ts
  src/components/Common/Button/PostFeedButton.tsx
  src/components/Common/Navigation/GlobalNavigation.tsx
  src/components/Feed/FeedEditModal.tsx
  src/components/PostForm/PostContent.tsx
  src/components/PostForm/PostContentShopItem.tsx
  src/components/PostForm/PostSearch.tsx
  src/components/PostForm/PostShopList.tsx
  src/hooks/queries/useRecommendQuery.ts
  src/hooks/queries/useRestaurantListQuery.ts
  src/hooks/useOnClickBack.ts
  src/hooks/useShowPartial.ts
  src/services/post.ts
  src/types/feed.ts
  src/types/post.ts
  tailwind.config.ts
Labels: 🎨 UI, ♻️ Refactor

#207 design: 비밀번호 가리기 on/off 적용 및 지도 기본 사이즈 적용
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Auth/PasswordAuth.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Map/MyListMap.tsx
  src/components/Settings/SettingPassword.tsx
  src/styles/globals.css
Labels: 🎨 UI

#211 refactor: Drawer 기능 추가 및 팔로워/팔로잉 목록에 Drawer 적용
  src/components/Common/Drawer/Drawer.tsx
  src/components/Mypage/MyFriendList.tsx
  src/components/Mypage/MyProfile.tsx
  src/styles/globals.css
Labels: 🎨 UI, ♻️ Refactor

#212 refactor: 메인 피드 페이지의 카테고리화 및 리팩토링
  src/app/main/feed/page.tsx
  src/app/main/home/page.tsx
  src/app/main/restaurants/[restaurantId]/feed/page.tsx
  src/components/Common/Button/FollowButton.tsx
  src/components/Feed/FeedUserCard.tsx
  src/components/Feed/Feeds.tsx
  src/components/Feed/FeedsCategoryList.tsx
  src/components/Feed/FeedsCategorySlider.tsx
  src/hooks/mutations/useFollowMutaton.ts
  src/hooks/queries/useFeedListQuery.ts
  src/utils/ReactQueryProvider.tsx
Labels: 🎨 UI, ♻️ Refactor

#213 fix: 식당 피드 리스트 팔로우 버튼 rerender 수정, 피드 리스트의 멀티, 싱글 피드 리스트 구분 로직 수정
  src/app/main/feed/page.tsx
  src/app/main/restaurants/[restaurantId]/feed/page.tsx
  src/components/Feed/FeedsCategoryList.tsx
  src/components/Restaurant/RestaurtandFeedsList.tsx
Labels: 🐛 Bug

#214 Refactor: 푸시 알림 리팩토링
  .eslintrc.json
  src/components/Common/Button/FollowButton.tsx
  src/components/Common/Thumbnail/FeedThumbnail.tsx
  src/components/Common/Thumbnail/FeedThumbnailList.tsx
  src/components/Common/Thumbnail/ImageThumbnail.tsx
  src/components/Common/Thumbnail/UserThumbnail.tsx
  src/components/Feed/FeedReplyItem.tsx
  src/components/Mypage/MyFeedThumnail.tsx
  src/components/Mypage/MyProfile.tsx
  src/components/Notification/NotifItem.tsx
  src/components/Notification/NotificationList.tsx
  src/components/PostForm/PostImageItems.tsx
  src/components/Restaurant/RestaurantFeedList.tsx
  src/components/Restaurant/ShopFeedItem.tsx
  src/hooks/mutations/useFollowMutaton.ts
  src/hooks/queries/useNotificationQuery.ts
  src/services/notification.ts
Labels: 🎨 UI, ♻️ Refactor

#216 [Refactor] #215 회원탈퇴 모달 스타일 수정
  src/components/Common/Dialog/CustomModal.tsx
  src/components/Settings/MySettings.tsx
  src/components/Settings/SettingWithdrawModal.tsx
  src/components/Settings/WithDrawReasonItem.tsx
  src/components/Settings/WithdrawModal.tsx
  src/constants/index.ts
  src/constants/withdraw.ts
  src/types/common.ts
  src/types/settings.ts
Labels: 🎨 UI, ♻️ Refactor

#220 fix: 웹팩 에러 해결 및 스타일 코드 수정
  next.config.js
  package-lock.json
  package.json
  src/assets/icons/common/bigcheckcircle.svg
  src/assets/icons/index.ts
  src/components/Auth/SignUpCode.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Auth/SignUpProfile.tsx
  src/components/Auth/SignUpTerms.tsx
  src/components/Auth/SignUpTermsModal.tsx
  src/components/Feed/FeedsCategoryList.tsx
  src/components/Restaurant/RestaurantCategorySlider.tsx
  src/components/Restaurant/RestaurantDetail.tsx
  src/types/common.ts
  src/utils/iconUtils.ts
Labels: 🐛 Bug

#221 fix: next 버전 업데이트 및 typescript용 eslint 적용
  .eslintrc.json
  next.config.js
  package-lock.json
  package.json
  src/components/Feed/FeedsCategorySlider.tsx
  src/components/Map/KakaoMap.tsx
  src/components/Map/MyListMap.tsx
  src/components/Map/common.ts
  src/components/Restaurant/RestaurantCategorySlider.tsx
Labels: 🐛 Bug

#222 Refactor: axios으로 마이그레이션 및 api 파일 정리
  src/components/Auth/AuthCheck.ts
  src/components/Common/Dialog/DialogReport.tsx
  src/components/Common/DropDown/DropDown.tsx
  src/components/Feed/FeedReplyInput.tsx
  src/components/Feed/FeedReplyItem.tsx
  src/components/Feed/FeedReplyList.tsx
  src/components/Feed/FeedShared.tsx
  src/components/Feed/Feeds.tsx
  src/components/Feed/FeedsCategoryList.tsx
  src/components/Map/KakaoMap.tsx
  src/components/Mypage/MyMap.tsx
  src/components/Notification/NotificationList.tsx
  src/components/Notification/PushNotification.ts
  src/components/Restaurant/RestaurantDetail.tsx
  src/components/SearchUser/SearchHistory.tsx
  src/components/SearchUser/SearchUser.tsx
  src/hooks/queries/useFeedListQuery.ts
  src/hooks/queries/useNotificationQuery.ts
  src/services/apiFeed.ts
  src/services/auth.ts
  src/services/feed.ts
  src/services/index.ts
  src/services/kakao.ts
  src/services/notification.ts
  src/services/reply.ts
  src/services/restaurant.ts
  src/types/apiTypes.ts
Labels: ♻️ Refactor

#227 feat: 메인 카테고리 api 연결
  src/components/Feed/FeedsCategoryList.tsx
  src/components/Feed/FeedsCategorySlider.tsx
  src/constants/tag.ts
  src/hooks/queries/useFeedListQuery.ts
  src/services/feed.ts
  src/types/restaurant.ts
Labels: ✨ Feature

#229 refactor: 빌드 오류 수정
  src/app/auth/kakao/callback/page.tsx
  src/app/entrance/page.tsx
  src/components/Auth/SignUpProfile.tsx
  src/components/Common/Toggle/index.tsx
  src/components/Mypage/MyFeedThumbnail.tsx
  src/components/Mypage/MyProfileSettings.tsx
  src/components/Mypage/MyProfileTabContent.tsx
  src/components/Notification/PushNotification.ts
  src/components/SearchUser/SearchHistory.tsx
  src/hooks/useOnClickBack.ts
  src/services/index.ts
  src/types/apiTypes.ts
  src/types/feed.ts
  src/utils/dummyDataUtils.ts
  src/utils/token.ts
Labels: ♻️ Refactor

#230 refactor: 피드 카테고리 페이지 리팩토링
  src/components/Feed/FeedsCategoryList.tsx
  src/hooks/queries/useFeedListQuery.ts
  src/services/feed.ts
Labels: 🎨 UI, ♻️ Refactor

#233 Refactor: 카카오 로그인 분기 처리 및 마이페이지 오류 수정
  src/app/auth/kakao/callback/page.tsx
  src/app/auth/kakao/page.tsx
  src/components/Auth/KaKaoTerms.tsx
  src/components/Mypage/MyFeedThumbnail.tsx
  src/components/Mypage/MyProfile.tsx
  src/components/Mypage/MyProfileSettings.tsx
  src/components/Notification/NotifItem.tsx
  src/constants/toast.ts
  src/services/kakao.ts
  src/services/mypage.ts
Labels: 🎨 UI, 🐛 Bug, ♻️ Refactor

#234 refactor: 타입 에러 수정
  src/components/Common/Input/SearchInput.tsx
  src/components/Mypage/MyFeedThumbnail.tsx
  src/components/Mypage/MyProfileSettings.tsx
  src/components/Restaurant/RestaurtandFeedsList.tsx
  src/services/restaurant.ts
  src/types/mypage.ts
Labels: 🐛 Bug

#236 refactor: 팔로우 뮤테이션 오류 수정 및 피드 썸네일 스크롤 적용
  src/assets/icons/common/Big_CheckCircle.svg
  src/assets/icons/index.ts
  src/components/Common/Button/FollowButton.tsx
  src/components/Mypage/MyFriendList.tsx
  src/components/Mypage/MyProfile.tsx
  src/components/Mypage/MyProfileTabContent.tsx
  src/hooks/mutations/useFollowMutaton.ts
Labels: 🐛 Bug, ♻️ Refactor

#238 Fix: localStorage 오류 및 useFollowMutation invalidateQueries 수정
  src/app/auth/kakao/callback/page.tsx
  src/app/auth/kakao/page.tsx
  src/components/Auth/KaKaoTerms.tsx
  src/components/Auth/SignUpProfile.tsx
  src/components/Notification/NotifItem.tsx
  src/hooks/mutations/useFollowMutaton.ts
  src/hooks/useLocalStorage.ts
Labels: 🐛 Bug, ♻️ Refactor

#240 [Feat] #205 대댓글, 멘션 기능 구현
  package-lock.json
  package.json
  src/components/Common/DropDown/DropDown.tsx
  src/components/Common/Profile/UserThumbImg.tsx
  src/components/Feed/FeedHeader.tsx
  src/components/Feed/FeedReplyInput.tsx
  src/components/Feed/FeedReplyItem.tsx
  src/components/Feed/FeedReplyList.tsx
  src/components/Feed/MentionItem.tsx
  src/components/Feed/ReplyContent.tsx
  src/components/SearchUser/SearchUserList.tsx
  src/constants/toast.ts
  src/hooks/mutations/useReplyMutation.ts
  src/hooks/queries/useReplyList.ts
  src/hooks/queries/useSearchUser.ts
  src/services/reply.ts
  src/styles/globals.css
  src/types/reply.ts
Labels: 🎨 UI, ♻️ Refactor, ✨ Feature

#241 refactor: api 수정 및 식당 필터링 로직 구현
  src/components/Map/MyMap.tsx
  src/components/Restaurant/RestaurantCategorySlider.tsx
  src/constants/tag.ts
  src/services/feed.ts
  src/services/restaurant.ts
Labels: ♻️ Refactor, ✨ Feature

#242 Feat: 푸시 알림 세부 설정 구현 및 카카오 로직 수정
  src/app/auth/kakao/callback/page.tsx
  src/app/main/settings/layout.tsx
  src/assets/icons/common/CaretRight.svg
  src/assets/icons/index.ts
  src/components/Common/Toggle/index.tsx
  src/components/Notification/NotifItem.tsx
  src/components/Settings/MySettings.tsx
  src/components/Settings/PushToggle.tsx
  src/components/Settings/SettingListItem.tsx
  src/components/Settings/SettingNotice.tsx
  src/constants/index.ts
  src/constants/settings.ts
  src/hooks/mutations/usePushMutation.ts
  src/hooks/useLocalStorage.ts
  src/services/settings.ts
  src/store/useNotificationStore.ts
  src/types/apiTypes.ts
  src/types/settings.ts
  src/utils/areAllNoticeY.ts
Labels: 🎨 UI, ♻️ Refactor, ✨ Feature

#249 [Feat] #244 대댓글 삭제 기능 문제 해결
  src/components/Feed/FeedReplyInput.tsx
  src/components/Feed/FeedReplyItem.tsx
  src/components/Feed/NestedReplyItem.tsx
Labels: ♻️ Refactor

#251 fix: 일반 로그인 토큰 로직 수정, 카테고리 etc 추가
  src/app/auth/kakao/callback/page.tsx
  src/components/Auth/AuthCheck.ts
  src/components/Auth/LoginForm.tsx
  src/components/Map/MyMap.tsx
  src/components/Restaurant/RestaurantCategorySlider.tsx
  src/constants/tag.ts
  src/types/restaurant.ts
  src/utils/date.ts
Labels: 🐛 Bug, ♻️ Refactor

#255 [Feat] #254 댓글 기능 추가
  src/assets/icons/common/send_able.svg
  src/assets/icons/common/send_disabled.svg
  src/assets/icons/index.ts
  src/components/Feed/FeedReplyInput.tsx
  src/components/Feed/FeedReplyList.tsx
Labels: ✨ Feature

#256 Refactor: useUserStore 알림 플래그 수정 및 신고 관련 컴포넌트 리팩토링
  src/components/Common/Dialog/DialogReport.tsx
  src/components/Common/DropDown/DropDown.tsx
  src/constants/settings.ts
  src/constants/toast.ts
  src/services/kakao.ts
  src/store/useUserStore.ts
  src/types/common.ts
Labels: ♻️ Refactor
