Repository FoodieLog/foodie-log-client, pull requests merged in 2024-04, with the labels that each got.

#257 refactor: 퓨전 및 기타 아이콘 추가
  src/assets/icons/index.ts
  src/assets/icons/tag/etc.svg
  src/assets/icons/tag/etc_selected.svg
  src/assets/icons/tag/fusion.svg
  src/assets/icons/tag/fusion_selected.svg
  src/components/Auth/AuthCheck.ts
  src/components/Restaurant/RestaurantCategorySlider.tsx
  src/constants/tag.ts
  src/types/restaurant.ts
Labels: 🎨 UI

#258 refactor: 타 회원 프로필 헤더 수정
  src/components/Mypage/MyProfile.tsx
Labels: ♻️ Refactor

#259 feat: 푸시 알림 API 연결
  src/components/Settings/PushToggle.tsx
Labels: ✨ Feature

#261 [Refactor] #260 지역별 맛집 추천 페이지 리팩토링
  src/components/Restaurant/ShopThumbList.tsx
  src/services/restaurant.ts
  src/types/restaurant.ts
Labels: ♻️ Refactor

#264 Fix: 카카오 로그인 오류
  src/app/auth/kakao/callback/page.tsx
  src/app/main/user/page.tsx
  src/components/Auth/AuthCheck.ts
  src/components/Auth/LoginForm.tsx
  src/hooks/useLocalStorage.ts
  src/services/kakao.ts
  src/store/useUserStore.ts
Labels: 🐛 Bug, ♻️ Refactor

#265 Refactor: 마이페이지 라우팅 경로 수정 및 피드 내 팔로우 버튼 조건부 랜더링
  src/app/auth/kakao/callback/page.tsx
  src/app/auth/kakao/page.tsx
  src/components/Auth/KaKaoTerms.tsx
  src/components/Common/Navigation/GlobalNavigation.tsx
  src/components/Common/Navigation/LeftSidebar.tsx
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedHeader.tsx
  src/components/Feed/FeedReplyContent.tsx
  src/components/Feed/FeedReplyItem.tsx
  src/components/Feed/FeedUserCard.tsx
  src/components/Feed/Feeds.tsx
  src/components/Feed/ReplyContent.tsx
  src/components/Mypage/MyProfile.tsx
  src/components/Mypage/MyProfileSettings.tsx
  src/components/PostForm/PostContent.tsx
  src/components/Restaurant/RestaurtandFeedsList.tsx
  src/constants/index.ts
  src/constants/navigation.ts
  src/hooks/useShowPartial.ts
Labels: ♻️ Refactor

#266 Release v2.3.1 - 오류 수정
  src/app/auth/kakao/callback/page.tsx
  src/app/auth/kakao/page.tsx
  src/app/main/user/page.tsx
  src/components/Auth/AuthCheck.ts
  src/components/Auth/KaKaoTerms.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Common/Navigation/GlobalNavigation.tsx
  src/components/Common/Navigation/LeftSidebar.tsx
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedHeader.tsx
  src/components/Feed/FeedReplyContent.tsx
  src/components/Feed/FeedReplyItem.tsx
  src/components/Feed/FeedUserCard.tsx
  src/components/Feed/Feeds.tsx
  src/components/Feed/ReplyContent.tsx
  src/components/Mypage/MyProfile.tsx
  src/components/Mypage/MyProfileSettings.tsx
  src/components/PostForm/PostContent.tsx
  src/components/Restaurant/RestaurtandFeedsList.tsx
  src/constants/index.ts
  src/constants/navigation.ts
  src/hooks/useLocalStorage.ts
  src/hooks/useShowPartial.ts
  src/services/kakao.ts
  src/store/useUserStore.ts
Labels: 🌏 Deploy

#269 Refactor- 헤더, 알림, firebase 파일 수정
  public/firebase-messaging-sw.js
  src/assets/images/index.ts
  src/assets/images/logo/mainLogo.png
  src/components/Common/Header/MainHeader.tsx
  src/components/Notification/NotifItem.tsx
  src/components/Notification/PushNotification.ts
  src/utils/truncateText.ts
Labels: ♻️ Refactor

#273 [Fix] #272 멘션 필터링 메서드 수정
  src/components/Feed/FeedReplyInput.tsx
  src/components/Feed/ReplyContent.tsx
Labels: ♻️ Refactor

#276 refactor: toast 표시 오류 및 FeedListQuery 무효화 오류 수정
  components/ui/use-toast.ts
  src/app/auth/kakao/callback/page.tsx
  src/components/Auth/LoginForm.tsx
  src/components/Common/Button/FollowButton.tsx
  src/components/Feed/FeedInteraction.tsx
  src/components/Feed/Feeds.tsx
  src/components/Mypage/MyProfile.tsx
  src/hooks/mutations/useFollowMutation.ts
  src/hooks/queries/useFeedListQuery.ts
Labels: 🐛 Bug, ♻️ Refactor

#277 refactor: 토스트 표시 후 페이지 이동 지연
  src/app/auth/kakao/callback/page.tsx
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/KaKaoTerms.tsx
  src/components/Auth/SignUpProfile.tsx
  src/components/Settings/WithdrawModal.tsx
Labels: ♻️ Refactor

#278 refactor: setTimeout delay 수정 및 스크롤 유지 로직 삭제
  src/app/auth/kakao/callback/page.tsx
  src/components/Auth/ChangePassword.tsx
  src/components/Auth/KaKaoTerms.tsx
  src/components/Auth/SignUpProfile.tsx
  src/components/Feed/Feeds.tsx
  src/components/Settings/WithdrawModal.tsx
Labels: ♻️ Refactor

#279 refactor: 1차 피드백 내용 수정
  public/liked.png
  public/restaurant.png
  src/components/Auth/AuthCheck.ts
  src/components/Common/Card/ShopCard.tsx
  src/components/Map/KakaoMap.tsx
  src/components/Map/MyListMap.tsx
  src/components/Map/MyMap.tsx
  src/components/Map/common.ts
  src/components/Mypage/MyMap.tsx
  src/components/Mypage/MyProfileTabContent.tsx
  src/components/Restaurant/RestaurantCategorySlider.tsx
  src/components/Restaurant/RestaurantDetail.tsx
  src/constants/tag.ts
  src/constants/toast.ts
  src/hooks/mutations/useLikeShopMutations.ts
  src/hooks/queries/useMyMapQuery.ts
  src/types/mypage.ts
  src/utils/date.ts
Labels: 🎨 UI, ♻️ Refactor

#280 Refactor: 카카오 로그인 토큰 재발급 및 로그아웃 수정
  src/app/auth/kakao/callback/page.tsx
  src/components/Auth/AuthCheck.ts
  src/hooks/useLogout.ts
Labels: ♻️ Refactor

#281 Refactor: 스켈레톤 일부 적용 및 마커, 오버레이 수정, 카카오 재발급 로직 수정
  public/liked.png
  public/restaurant.png
  src/assets/images/basic/basic_thumb.png
  src/components/Auth/AuthCheck.ts
  src/components/Common/Skeleton/index.tsx
  src/components/Feed/FeedsCategoryList.tsx
  src/components/Map/MyListMap.tsx
  src/components/Map/MyMap.tsx
  src/components/Restaurant/RestaurantDetail.tsx
Labels: ♻️ Refactor

#283 Refactor: AuthCheck 로직 수정
  src/components/Auth/AuthCheck.ts
Labels: ♻️ Refactor

#284 refactor: 카카오로그인 에러시 카카오로그아웃
  src/app/auth/kakao/callback/page.tsx
  src/components/Auth/AuthCheck.ts
Labels: ♻️ Refactor

#285 Release v2.0.3 - 오류수정
  src/app/auth/kakao/callback/page.tsx
  src/components/Auth/AuthCheck.ts
Labels: 🌏 Deploy

#286 Refactor: 아이콘 파일명 변경
  public/liked.png
  public/restaurant.png
Labels: ♻️ Refactor

#287 Release v2.0.3: 아이콘 파일명 수정
  public/liked.png
  public/restaurant.png
Labels: 🌏 Deploy

#288 Refactor: 번들 사이즈 축소를 위해 아이콘 Default import로 수정
  src/app/main/recommend/reviews/[id]/page.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Auth/SignUpTermsDrawer.tsx
  src/components/Common/Button/BackButton.tsx
  src/components/Common/Button/FollowButton.tsx
  src/components/Common/Button/PostFeedButton.tsx
  src/components/Common/Card/ShopCard.tsx
  src/components/Common/DropDown/DropDown.tsx
  src/components/Common/Error/index.tsx
  src/components/Common/Header/MainHeader.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/Input/SearchInput.tsx
  src/components/Common/Input/index.tsx
  src/components/Common/Navigation/GlobalNavigation.tsx
  src/components/Common/Navigation/LeftSidebar.tsx
  src/components/Common/Profile/UserThumbImg.tsx
  src/components/Common/Thumbnail/ImageThumbnail.tsx
  src/components/Feed/FeedContent.tsx
  src/components/Feed/FeedImageSlide.tsx
  src/components/Feed/FeedInteraction.tsx
  src/components/Feed/FeedReplyInput.tsx
  src/components/Feed/FeedReplyList.tsx
  src/components/Mypage/MyProfileImage.tsx
  src/components/PostForm/EmptyList.tsx
  src/components/PostForm/PostContentShopItem.tsx
  src/components/PostForm/PostFeedImage.tsx
  src/components/PostForm/PostImageItems.tsx
  src/components/PostForm/PostShopItem.tsx
  src/components/Restaurant/RestaurantCategorySlider.tsx
  src/components/Restaurant/RestaurantFeedList.tsx
  src/components/SearchUser/SearchHistory.tsx
  src/components/Settings/CompleteChangePassword.tsx
  src/components/Settings/SettingBadge.tsx
  src/components/Settings/SettingListItem.tsx
  src/components/Settings/SettingPassword.tsx
  src/components/Settings/WithDrawReasonItem.tsx
  src/constants/navigation.ts
  src/store/useKakaoStore.ts
  src/utils/iconUtils.ts
  src/utils/token.ts
Labels: ♻️ Refactor

#290 [Refactor] #289 디자인 수정
  src/app/main/recommend/page.tsx
  src/app/main/recommend/reviews/[id]/page.tsx
  src/app/main/settings/layout.tsx
  src/components/Common/Input/SearchInput.tsx
  src/components/PostForm/PostSearch.tsx
  src/components/SearchUser/SearchUser.tsx
  src/components/Settings/MySettings.tsx
  src/components/Settings/SettingBadge.tsx
  src/components/Settings/SettingPassword.tsx
Labels: 🎨 UI

#293 refactor: 피드백 2차 수정
  src/app/main/layout.tsx
  src/app/main/liked/page.tsx
  src/assets/images/basic/no_img.png
  src/assets/images/index.ts
  src/components/Map/MyMap.tsx
  src/components/Restaurant/RestaurantDetail.tsx
Labels: ♻️ Refactor

#294 fix: 새로고침 시 로그아웃되는 에러 및 <P> 태그 중첩 에러 해결
  src/components/Auth/AuthCheck.ts
  src/components/Auth/SignUpForm.tsx
  src/components/Common/Button/FollowButton.tsx
  src/components/Feed/FeedUserCard.tsx
  src/services/kakao.ts
Labels: 🐛 Bug

#295 Refactor: firebase import 오류 및 로그인 toast 오류 수정
  public/firebase-messaging-sw.js
  src/components/Auth/LoginForm.tsx
Labels: 🐛 Bug

#296 Release v2.0.4 - QA 수정사항 반영 (새로고침시 로그아웃 오류 등)
  public/firebase-messaging-sw.js
  src/app/main/layout.tsx
  src/app/main/liked/page.tsx
  src/app/main/recommend/page.tsx
  src/app/main/recommend/reviews/[id]/page.tsx
  src/app/main/settings/layout.tsx
  src/assets/images/basic/no_img.png
  src/assets/images/index.ts
  src/components/Auth/AuthCheck.ts
  src/components/Auth/LoginForm.tsx
  src/components/Auth/SignUpForm.tsx
  src/components/Auth/SignUpTermsDrawer.tsx
  src/components/Common/Button/BackButton.tsx
  src/components/Common/Button/FollowButton.tsx
  src/components/Common/Button/PostFeedButton.tsx
  src/components/Common/Card/ShopCard.tsx
  src/components/Common/DropDown/DropDown.tsx
  src/components/Common/Error/index.tsx
  src/components/Common/Header/MainHeader.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/Input/SearchInput.tsx
  src/components/Common/Input/index.tsx
  src/components/Common/Navigation/GlobalNavigation.tsx
  src/components/Common/Navigation/LeftSidebar.tsx
  src/components/Common/Profile/UserThumbImg.tsx
  src/components/Common/Thumbnail/ImageThumbnail.tsx
  src/components/Feed/FeedContent.tsx
  src/components/Feed/FeedImageSlide.tsx
  src/components/Feed/FeedInteraction.tsx
  src/components/Feed/FeedReplyInput.tsx
  src/components/Feed/FeedReplyList.tsx
  src/components/Feed/FeedUserCard.tsx
  src/components/Map/MyMap.tsx
  src/components/Mypage/MyProfileImage.tsx
  src/components/PostForm/EmptyList.tsx
  src/components/PostForm/PostContentShopItem.tsx
  src/components/PostForm/PostFeedImage.tsx
  src/components/PostForm/PostImageItems.tsx
  src/components/PostForm/PostSearch.tsx
  src/components/PostForm/PostShopItem.tsx
  src/components/Restaurant/RestaurantCategorySlider.tsx
  src/components/Restaurant/RestaurantDetail.tsx
  src/components/Restaurant/RestaurantFeedList.tsx
  src/components/SearchUser/SearchHistory.tsx
  src/components/SearchUser/SearchUser.tsx
  src/components/Settings/CompleteChangePassword.tsx
  src/components/Settings/MySettings.tsx
  src/components/Settings/SettingBadge.tsx
  src/components/Settings/SettingListItem.tsx
  src/components/Settings/SettingPassword.tsx
  src/components/Settings/WithDrawReasonItem.tsx
  src/constants/area.ts
  src/constants/navigation.ts
  src/services/kakao.ts
  src/store/useKakaoStore.ts
  src/utils/iconUtils.ts
  src/utils/token.ts
Labels: 🌏 Deploy

#299 Feat: 맛잘알 뱃지 표시 구현
  src/assets/icons/common/Badge.svg
  src/components/Feed/FeedUserCard.tsx
  src/components/Mypage/MyProfile.tsx
  src/components/SearchUser/SearchUserList.tsx
  src/store/useUserStore.ts
  src/types/apiTypes.ts
Labels: ✨ Feature

#300 Release v2.0.4 - 뱃지 기능 추가
  README.md
  src/assets/icons/common/Badge.svg
  src/components/Feed/FeedUserCard.tsx
  src/components/Mypage/MyProfile.tsx
  src/components/SearchUser/SearchUserList.tsx
  src/store/useUserStore.ts
  src/types/apiTypes.ts
Labels: 🌏 Deploy
