Repository FoodieLog/foodie-log-client, pull requests merged in 2024-02, with the labels that each got.

#145 feat: jest 테스팅 환경 설정
  __test__/feed.test.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  tsconfig.json
Labels: ⚙ Setting

#150 [Refactor] #147 피드 작성 페이지 리팩토링
  src/components/PostForm/PostContent.tsx
  src/components/PostForm/PostImage.tsx
  src/components/PostForm/PostSearch.tsx
  src/components/PostForm/PostShopList.tsx
  src/store/usePostStore.ts
  src/types/post.ts
Labels: ♻️ Refactor

#153 [Refactor] #151 지역별 맛집 추천 페이지 리팩토링
  src/app/main/recommend/page.tsx
  src/components/Restaurant/AreaList.tsx
  src/components/Restaurant/AreaOptionItem.tsx
  src/components/Restaurant/AreaSelector.tsx
  src/components/Restaurant/ShopFeedItem.tsx
  src/components/Restaurant/ShopFeedList.tsx
  src/components/Restaurant/ShopThumb.tsx
  src/components/Restaurant/ShopThumbList.tsx
  src/constants/area.ts
  src/constants/index.ts
  src/services/apiRestaurant.ts
  src/types/apiTypes.ts
  src/types/recommend.ts
Labels: ♻️ Refactor

#160 [Release] dev 변경사항을 main에 적용
  .github/ISSUE_TEMPLATE/issue-탬플릿.md
  .github/pull_request_template.md
  README.md
  __test__/feed.test.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  src/app/main/recommend/page.tsx
  src/components/Map/KakaoMap.tsx
  src/components/Map/MyListMap.tsx
  src/components/Map/common.ts
  src/components/PostForm/PostContent.tsx
  src/components/PostForm/PostImage.tsx
  src/components/PostForm/PostSearch.tsx
  src/components/PostForm/PostShopList.tsx
  src/components/Restaurant/AreaList.tsx
  src/components/Restaurant/AreaOptionItem.tsx
  src/components/Restaurant/AreaSelector.tsx
  src/components/Restaurant/ShopFeedItem.tsx
  src/components/Restaurant/ShopFeedList.tsx
  src/components/Restaurant/ShopThumb.tsx
  src/components/Restaurant/ShopThumbList.tsx
  src/constants/area.ts
  src/constants/index.ts
  src/services/apiRestaurant.ts
  src/store/usePostStore.ts
  src/types/apiTypes.ts
  src/types/post.ts
  src/types/recommend.ts
  tsconfig.json
Labels: 🌏 Deploy

#155 [Refactor]: Feed 관련 컴포넌트 리팩토링
  src/app/main/reply/[id]/page.tsx
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedEditModal.tsx
  src/components/Feed/FeedImageSlide.tsx
  src/components/Feed/FeedShared.tsx
  src/components/Feed/Feeds.tsx
  src/components/Feed/replyList.tsx
  src/services/feed.ts
  src/services/reply.ts
  src/styles/feedStyle.ts
  src/types/feed.ts
  src/types/reply.ts
  tsconfig.json
Labels: ♻️ Refactor

#158 [Refactor] #157 개인 정보 수정 페이지 리팩토링
  src/components/Settings/MySettings.tsx
  src/components/Settings/SettingBadge.tsx
  src/components/Settings/SettingPassword.tsx
  src/components/Settings/SettingWithdrawModal.tsx
Labels: ♻️ Refactor

#165 [Refactor] #164 tsconfig paths 설정 및 적용
  src/app/main/post/page.tsx
  src/app/main/reply/[id]/page.tsx
  src/components/Feed/FeedReplyList.tsx
  src/components/PostForm/PostContent.tsx
  src/components/PostForm/PostImage.tsx
  src/components/PostForm/PostSearch.tsx
  src/components/PostForm/PostShopItem.tsx
  src/components/PostForm/PostShopList.tsx
  src/components/Restaurant/AreaList.tsx
  src/components/Restaurant/AreaOptionItem.tsx
  src/components/Restaurant/AreaSelector.tsx
  src/components/Restaurant/ShopFeedItem.tsx
  src/components/Restaurant/ShopFeedList.tsx
  src/components/Restaurant/ShopThumb.tsx
  src/components/Restaurant/ShopThumbList.tsx
  src/components/Settings/MySettings.tsx
  src/components/Settings/SettingBadge.tsx
  src/components/Settings/SettingPassword.tsx
  src/components/Settings/SettingWithdrawModal.tsx
  tsconfig.json
Labels: ♻️ Refactor

#167 Refactor: 스타일 테마 커스터마이징 및 아이콘, 썸네일 파일 저장
  src/app/layout.tsx
  src/assets/icons/common/CaretDown.png
  src/assets/icons/common/ChatCircleText.png
  src/assets/icons/common/Frame 427320831.png
  src/assets/icons/common/Frame 427320832.png
  src/assets/icons/common/Frame 427320833.png
  src/assets/icons/common/Frame 427320834.png
  src/assets/icons/common/Frame 427320836.png
  src/assets/icons/common/Frame 427320840.png
  src/assets/icons/common/Frame 427320841.png
  src/assets/icons/common/Frame 427320871.png
  src/assets/icons/common/Frame 427320873.png
  src/assets/icons/common/Heart.png
  src/assets/icons/common/ShareFat.png
  src/assets/icons/common/arrow_back_ios.png
  src/assets/icons/common/autorenew-1.png
  src/assets/icons/common/autorenew.png
  src/assets/icons/common/favorite.png
  src/assets/icons/common/imagesmode.png
  src/assets/icons/common/location_on.png
  src/assets/icons/common/lock_reset.png
  src/assets/icons/common/logout.png
  src/assets/icons/common/military_tech.png
  src/assets/icons/common/notifications-1.png
  src/assets/icons/common/notifications-2.png
  src/assets/icons/common/notifications.png
  src/assets/icons/common/open_in_new.png
  src/assets/icons/common/restaurant-1.png
  src/assets/icons/common/restaurant.png
  src/assets/icons/common/search.png
  src/assets/icons/common/sentiment_very_dissatisfied.png
  src/assets/icons/common/settings.png
  src/assets/thumbnail/restaurants/asian.png
  src/assets/thumbnail/restaurants/bar.png
  src/assets/thumbnail/restaurants/cafe.png
  src/assets/thumbnail/restaurants/dessert.png
  src/assets/thumbnail/restaurants/japanese.png
  src/assets/thumbnail/restaurants/korean.png
  src/assets/thumbnail/restaurants/snack.png
  src/assets/thumbnail/restaurants/western.png
  src/components/Common/Button/AuthButton.tsx
  src/components/Mypage/MyFriendList.tsx
  src/components/PostForm/PostContent.tsx
  src/hooks/mutations/useMutaton.ts
  src/hooks/queries/useQuery.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: ⚙ Setting

#171 chore: 아이콘 (Common, GNB) / 이미지 (식당 썸네일) 추가 및 모듈 생성
  src/assets/icons/common/CheckCircle.png
  src/assets/icons/common/Frame 427320831.png
  src/assets/icons/common/Frame 427320832.png
  src/assets/icons/common/Frame 427320833.png
  src/assets/icons/common/Frame 427320834.png
  src/assets/icons/common/Frame 427320836.png
  src/assets/icons/common/Frame 427320840.png
  src/assets/icons/common/Frame 427320841.png
  src/assets/icons/common/Frame 427320871.png
  src/assets/icons/common/Frame 427320873.png
  src/assets/icons/common/HeartStraight-2.png
  src/assets/icons/common/HeartStraight.png
  src/assets/icons/common/HeartWithCircle.png
  src/assets/icons/common/Phone-2.png
  src/assets/icons/common/Phone.png
  src/assets/icons/common/WarningCircle.png
  src/assets/icons/common/autorenew-2.png
  src/assets/icons/common/dissatisfied.png
  src/assets/icons/common/location_on-2.png
  src/assets/icons/common/notifications-1.png
  src/assets/icons/common/notifications.png
  src/assets/icons/common/photo_camera.png
  src/assets/icons/gnb/map.png
  src/assets/icons/gnb/map_check.png
  src/assets/icons/gnb/person.png
  src/assets/icons/gnb/person_check.png
  src/assets/icons/gnb/space_dashboard.png
  src/assets/icons/gnb/space_dashboard_check.png
  src/assets/icons/gnb/thumb_up.png
  src/assets/icons/gnb/thumb_up_check.png
  src/assets/icons/index.ts
  src/assets/images/index.ts
  src/assets/images/restaurants/asian.png
  src/assets/images/restaurants/bar.png
  src/assets/images/restaurants/cafe.png
  src/assets/images/restaurants/dessert.png
  src/assets/images/restaurants/japanese.png
  src/assets/images/restaurants/korean.png
  src/assets/images/restaurants/snack.png
  src/assets/images/restaurants/western.png
Labels: 📃 Docs

#172 refactor: 색상 넘버 수정
  tailwind.config.ts
Labels: ♻️ Refactor, ⚙ Setting

#173 [Design] #170 공통 컴포넌트 수정 디자인 적용
  components/ui/dropdown-menu/index.tsx
  src/app/main/layout.tsx
  src/assets/icons/common/add.png
  src/assets/icons/index.ts
  src/components/Common/DropDown/DropDown.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/ImageThumbnail/index.tsx
  src/components/Common/TextArea/index.tsx
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedReplyList.tsx
  src/components/Feed/ReplyItem.tsx
  src/components/Main/Bottombar.tsx
  src/components/Main/GlobalNavigation.tsx
  src/components/Main/LeftSidebar.tsx
  src/components/Mypage/MyProfile.tsx
  src/components/Mypage/MyProfileImage.tsx
  src/components/Mypage/MyProfileSettings.tsx
  src/components/PostForm/PostContent.tsx
  src/components/PostForm/PostFeedImage.tsx
  src/components/PostForm/PostImage.tsx
  src/components/PostForm/PostImageItems.tsx
  src/components/PostForm/PostImageList.tsx
  src/constants/index.ts
  src/constants/navigation.ts
  src/types/common.ts
  src/types/navigation.ts
  src/types/post.ts
  src/types/reply.ts
Labels: 🎨 UI, ♻️ Refactor

#178 Refactor: 검색 관련 컴포넌트 리팩토링 및 useDebounce 훅 생성
  src/components/PostForm/PostSearch.tsx
  src/components/SearchUser/SearchInput.tsx
  src/components/SearchUser/SearchUser.tsx
  src/hooks/useDebounce.ts
Labels: ♻️ Refactor, ✨ Feature
